### PR TITLE
Supporting April Hathcock

### PR DESCRIPTION
**Pull request by andreakb**
I thought it might be a good idea to draft a post of support for April Hathcock, as the ALA isn't specifically a digpres space, but it overlaps, yeah? Edit as you see fit

### CODE REVIEW

**Comment by sromkey** [comment]
I'm supportive of this and I think it's wonderfully written @andreakb

**Comment by ablwr** [comment]
Indeed!

**Comment by kfrn** [comment]
This is great, Andrea!

**Comment by ross-spencer** [comment]
This is nicely-written @andreakb. Before hitting go, do you have time to reach out to April to just let her know the intent to publish this and give her final say on what we're writing?

**Comment by andreakb** [comment]
Absolutely, @ross-spencer!

**Comment by andreakb** [comment]
April responded to thank us for our support and suggested an edit about ALA's response to her. I made the change and I will post it when I hear back about the edit.  Thanks everyone!

**Comment by ross-spencer** [comment]
LGTM! :+1:

**Pull request merged**
